### ISSUE TITLE
navigating and jumping to pages

### ISSUE THREAD

**Issue by jtkeyva** [caseyryan/flutter_instagram_storyboard#2]
is there any way to advance pages programatically and listen for pagechanges? can i create a button to move to the next and previous page? or a button that jumps directly to a specific page?

thanks

**Comment by caseyryan** [comment]
Yes. When you create a StoryButtonData , you can pass a controller there
```dart
storyController
```
And the controller has has methods previousSegment and nextSegment. You can use them for your purpose. 
I think it's not the most handy implementation but I don't have time to support this package at the moment, unfortunately
