### ISSUE TITLE
StoryTimelineController error 

### ISSUE THREAD

**Issue by jeetsdev** [caseyryan/flutter_instagram_storyboard#3]
I am not able to import StoryTimelineController, Flutter is not able to find the controller in the package, and also I am not able to find any way to execute some custom code after a particular story is watched.

**Comment by caseyryan** [comment]
It's inside story_button.dart file. Just import the package and it will be there

**Comment by jeetsdev** [comment]
Thank you @caseyryan
Just a small correction, We have to import "story_page_container_view.dart"  to use StoryTimelineController.
Again Thanks for the package, it's really helpful.
