### ISSUE TITLE
How to save status of watched stories after restarting 

### ISSUE THREAD

**Issue by azappz** [caseyryan/flutter_instagram_storyboard#5]
hello friend
did your package gave any way to save watched stories when restart the app it reset storyWatchedContract !
storyWatchedContract: StoryWatchedContract.onStoryEnd, 
there are no way to update some value or executing a function after watching story or saving storyWatchedContract status

**Comment by caseyryan** [comment]
Hello,
No, persistence is up to a developer. The package provides no way of storing a value
